nbde_client_bindings:
  - device: /dev/sda2
    encryption_password: "{{ nbde_encryption_password_vault }}"
    servers:
      - http://containerhost1.demo.net:8080
      - http://containerhost2.demo.net:8080
